name: Pull Request Packer test

on:
  pull_request:
    branches:
      - main

jobs: 
  pull-request-ami-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Setup Packer
          uses: hashicorp/setup-packer@main
          id: setup
          with:
            version: "latest"

        - name: Check Packer version
          run: packer version

        - name: Go to file location
          run: |
            pwd
            ls -la
            cd webapp
            ls -la

        - name: Packer init
          run: |
            pwd
            ls -la
            cd webapp
            ls -la
            packer init ./aws-debian.pkr.hcl
        - name: Check hcl format
          run: |
            pwd
            ls -la
            cd webapp
            ls -la
            packer version
            output=$(packer fmt ./aws-debian.pkr.hcl)
            if [ -n "$output" ]; then
              echo "Packer file has been modified. Found issues with the formatting:"
              echo "$output"
              exit 1
            fi
        - name: Validate packer file
          run: |
            pwd
            ls -la
            cd webapp
            ls -la
            packer validate -var "aws_region=${{ vars.AWS_REGION_PACKER }}" -var "source_ami=${{ vars.SOURCE_AMI_PACKER }}" -var "ssh_username=${{ vars.SSH_USERNAME_PACKER }}" -var "subnet_id=${{ vars.SUBNET_ID_PACKER }}" -var "ami_users=${{ vars.AMI_USERS_PACKER }}" -var "instance_type=${{ vars.INSTANCE_TYPE_PACKER }}" -var "volume_size=${{ vars.VOLUME_SIZE_PACKER }}" -var "volume_type=${{ vars.VOLUME_TYPE_PACKER }}" -var "delay_seconds=${{ vars.DELAY_SECONDS_PACKER }}" -var "max_attempts=${{ vars.MAX_ATTEMPTS_PACKER }}" ./aws-debian.pkr.hcl
