name: Pull Request Packer test

on:
  pull_request:
    branches:
      - main

jobs: 
  pull-request-ami-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Setup Packer
          uses: hashicorp/setup-packer@main
          id: setup
          with:
            version: "latest"

        - name: Check Packer version
          run: packer version

        - name: Go to file location
          run: |
            pwd
            ls -la
            cd webapp
            ls -la

        - name: Packer init
          run: |
            pwd
            ls -la
            cd webapp
            ls -la
            packer init ./aws-debian.pkr.hcl
        - name: Check hcl format
          run: |
            pwd
            ls -la
            cd webapp
            ls -la
            packer version
            output=$(packer fmt ./aws-debian.pkr.hcl)
            if [ -n "$output" ]; then
              echo "Packer file has been modified. Found issues with the formatting:"
              echo "$output"
              exit 1
            fi
        - name: Validate packer file
          run: |
            pwd
            ls -la
            cd webapp
            ls -la
            expected_output="The configuration is valid."
            output=$(packer validate ./aws-debian.pkr.hcl)
            if [[ "$output" != "$expected_output" ]]; then
              echo "Packer validation failed. Found some errors:"
              echo "$output"
              exit 1
            fi
            
