name: Merge Request Packer test

on:
  pull_request:
    branches:
      - main

jobs: 
  build-and-deploy-ami:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-1

           # Initialize Packer templates
        - name: Initialize Packer Template
          uses: hashicorp/packer-github-actions@master
          with:
            command: init
            target: webapp/webapp/aws-debian.pkr.hcl

        - name: Check packer version
          run: packer version
