name: Merge Request Packer test

on:
  pull_request:
    branches:
      - main

jobs: 
  build-and-deploy-ami:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:14
          env:
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          ports:
            - 5432:5432
          options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
          
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        
