name: Pull Request Integration Test

on:
  pull_request:
    branches:
      - main

jobs: 
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11

        - name: Install dependencies
          run: |
            pwd
            cd webapp
            ls -la
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Move users.csv to /opt
          run: |
            cd webapp
            mv users.csv /opt
            ls -la /opt

        - name: Run tests (PostgreSQL)
          run: |
            cd webapp
            ls -la
            python IntegrationTest.py
